orders:
  resource:
    path: ../src/Order/Routes
    namespace: App\Order\Routes
  type: attribute

health_checks:
  resource:
    path: ../src/HealthCheck/
    namespace: App\HealthCheck
  type: attribute
